export const ID = {
  LOGIN_ACTION: 'LOGIN_ACTION',
  LOGIN_ACTION_WITH_FOOTER: 'LOGIN_ACTION_WITH_FOOTER',
  CHANGE_ADDRESS_ACTION: 'CHANGE_ADDRESS_ACTION',
};

export const ACTION_SIZE = {
  LOGIN_ACTION: 235,
  LOGIN_ACTION_WITH_FOOTER: 450,
  CHANGE_ADDRESS_ACTION: 320,
};

export const SIDEBAR_SIZE = 320;
